# Generated by Django 5.1.2 on 2024-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
